### PR TITLE
Clean up default kubeconfig on cluster delete

### PR DESCRIPTION
**Pull request by michaellopez**
This PR adds clean up of the default kubeconfig. Upon cluster creation one can set `update_default_kubeconfig` and that will update the default kubeconfig. However on cluster deletion, currently that update remains. The k3d CLI always cleans up the default kubeconfig on `k3d cluster delete <name>`. This PR follows the [same logic as the k3d CLI](https://github.com/k3d-io/k3d/blob/5b26a4cf28f17c2bf6a9c9f3857854fd3076713d/cmd/cluster/clusterDelete.go#L70)

Tested locally through [filesystem mirror config](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-installation) in `~/.terraformrc` on an M1 Mac.

Also, I checked `internal/provider/resource_cluster_test.go` but there wasn't any test similar to my proposed change here. Not sure how to handle the side effect of the kubeconfig file in the tests. If the test is required to merge this PR, I'd like a bit of guidance as to how I should approach it. Thanks!

### CODE REVIEW

**Review by a-manraj-pvotal — CHANGES_REQUESTED** [review]
v1alpha4.SimpleConfig -> v1alpha5.SimpleConfig ?

**Comment by michaellopez** [comment]
> v1alpha4.SimpleConfig -> v1alpha5.SimpleConfig ?

Yes, of course, now that #78 is merged. Nice catch. I will fix

**Comment by michaellopez** [comment]
@a-manraj-pvotal I updated to `v1alpha5`

**Review by a-manraj-pvotal — APPROVED** [review]

**Comment by michaellopez** [comment]
@a-manraj-pvotal can we get a new release pushed to the Terraform registry?

**Pull request merged**
